server:
  port: 8080 # El único puerto al que le haremos peticiones en Postman

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para ms-subscription
        - id: ms-subscription-route
          uri: lb://ms-subscription
          predicates:
            - Path=/api/subscriptions/**

        # Ruta para ms-member
        - id: ms-member-route
          uri: lb://ms-member
          predicates:
            - Path=/api/members/**

        # Ruta para ms-employee
        - id: ms-employee-route
          uri: lb://ms-employee
          predicates:
            - Path=/api/employees/**

        # Ruta para ms-billing
        - id: ms-billing-route
          uri: lb://ms-billing
          predicates:
            - Path=/api/billings/**

        # Ruta para ms-access
        - id: ms-access-route
          uri: lb://ms-access
          predicates:
            - Path=/api/accesses/**

        # Ruta para ms-notification
        - id: ms-notification-route
          uri: lb://ms-notification
          predicates:
            - Path=/api/notifications/**

        # Ruta para ms-auth
        - id: ms-auth-route
          uri: lb://ms-auth
          predicates:
            - Path=/api/auth/**

        # Ruta para ms-inventory
        - id: ms-inventory-route
          uri: lb://ms-inventory
          predicates:
            - Path=/api/inventories/**

        # Ruta para ms-workout
        - id: ms-workout-route
          uri: lb://ms-workout
          predicates:
            - Path=/api/workouts/**

        # Ruta para ms-scheduling
        - id: ms-scheduling-route
          uri: lb://ms-scheduling
          predicates:
            - Path=/api/schedules/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
