INSERT IGNORE INTO accesses (member_id, access_date_time, granted, denial_reason) VALUES (1, '2026-05-17 08:30:00', true, NULL);
INSERT IGNORE INTO accesses (member_id, access_date_time, granted, denial_reason) VALUES (2, '2026-05-17 09:15:00', false, 'MEMBRESIA EXPIRED O MOROSO');
INSERT IGNORE INTO accesses(member_id, access_date_time, granted, denial_reason) VALUES (3, '2026-05-17 10:00:00', true, NULL);
INSERT IGNORE INTO accesses (member_id, access_date_time, granted, denial_reason) VALUES (1, '2026-05-17 08:30:00', true, NULL);
INSERT IGNORE INTO accesses (member_id, access_date_time, granted, denial_reason) VALUES (2, '2026-05-17 09:15:00', false, 'MEMBRESIA EXPIRED O MOROSO');
INSERT IGNORE INTO accesses(member_id, access_date_time, granted, denial_reason) VALUES (3, '2026-05-17 10:00:00', true, NULL);
INSERT IGNORE INTO credentials (username, password_hash, role, active) VALUES ('daedo@correo.cl', '$2a$10$xyzSimulatedHashAdmin123', 'ADMIN', true);
INSERT IGNORE INTO credentials (username, password_hash, role, active) VALUES ('pcespedes@correo.cl', '$2a$10$xyzSimulatedHashUser456', 'USER', true);
INSERT IGNORE INTO credentials (username, password_hash, role, active) VALUES ('daedo@correo.cl', '$2a$10$xyzSimulatedHashAdmin123', 'ADMIN', true);
INSERT IGNORE INTO credentials (username, password_hash, role, active) VALUES ('pcespedes@correo.cl', '$2a$10$xyzSimulatedHashUser456', 'USER', true);
INSERT IGNORE INTO billings (member_id, subscription_id, issue_date, due_date, total_amount, status) VALUES (1, 3, '2026-05-01', '2026-05-10', 200000, 'PAID');
INSERT IGNORE INTO billings (member_id, subscription_id, issue_date, due_date, total_amount, status) VALUES (2, 1, '2026-05-15', '2026-05-25', 25000, 'PENDING');
INSERT IGNORE INTO billings (member_id, subscription_id, issue_date, due_date, total_amount, status) VALUES (1, 3, '2026-05-01', '2026-05-10', 200000, 'PAID');
INSERT IGNORE INTO billings (member_id, subscription_id, issue_date, due_date, total_amount, status) VALUES (2, 1, '2026-05-15', '2026-05-25', 25000, 'PENDING');
INSERT IGNORE INTO employees (rut, first_name, last_name, email, role, active) VALUES ('15111222-3', 'Mauricio', 'GonzÃ¡lez', 'mgonzalez@sportmedics.cl', 'ADMIN', true);
INSERT IGNORE INTO employees (rut, first_name, last_name, email, role, active) VALUES ('17444555-6', 'Carla', 'PÃ©rez', 'cperez@sportmedics.cl', 'TEACHER', true);
INSERT IGNORE INTO employees (rut, first_name, last_name, email, role, active) VALUES ('19888999-0', 'Luis', 'SÃ¡nchez', 'lsanchez@sportmedics.cl', 'RECEPTIONIST', true);
INSERT IGNORE INTO employees (rut, first_name, last_name, email, role, active) VALUES ('15111222-3', 'Mauricio', 'GonzÃ¡lez', 'mgonzalez@sportmedics.cl', 'ADMIN', true);
INSERT IGNORE INTO employees (rut, first_name, last_name, email, role, active) VALUES ('17444555-6', 'Carla', 'PÃ©rez', 'cperez@sportmedics.cl', 'TEACHER', true);
INSERT IGNORE INTO employees (rut, first_name, last_name, email, role, active) VALUES ('19888999-0', 'Luis', 'SÃ¡nchez', 'lsanchez@sportmedics.cl', 'RECEPTIONIST', true);
INSERT IGNORE INTO inventory_items (name, category, quantity, location, active) VALUES ('Cinta de Correr Pro', 'MACHINES', 5, 'Zona Cardio', true);
INSERT IGNORE INTO inventory_items (name, category, quantity, location, active) VALUES ('Mancuernas 10kg', 'WEIGHTS', 12, 'Zona Peso Libre', true);
INSERT IGNORE INTO inventory_items (name, category, quantity, location, active) VALUES ('Colchoneta Yoga', 'ACCESSORIES', 20, 'Sala Clases Grupales', true);
INSERT IGNORE INTO inventory_items (name, category, quantity, location, active) VALUES ('Cinta de Correr Pro', 'MACHINES', 5, 'Zona Cardio', true);
INSERT IGNORE INTO inventory_items (name, category, quantity, location, active) VALUES ('Mancuernas 10kg', 'WEIGHTS', 12, 'Zona Peso Libre', true);
INSERT IGNORE INTO inventory_items (name, category, quantity, location, active) VALUES ('Colchoneta Yoga', 'ACCESSORIES', 20, 'Sala Clases Grupales', true);
INSERT IGNORE INTO members (rut, first_name, last_name, email, phone, active) VALUES ('19123456-7', 'Daniel', 'Aedo', 'daedo@correo.cl', '+56912345678', true);
INSERT IGNORE INTO members (rut, first_name, last_name, email, phone, active) VALUES ('19765432-1', 'Patricio', 'CÃ©spedes', 'pcespedes@correo.cl', '+56987654321', true);
INSERT IGNORE INTO members (rut, first_name, last_name, email, phone, active) VALUES ('20111222-3', 'Angelo', 'Ponce', 'aponce@correo.cl', '+56911223344', true);
INSERT IGNORE INTO members (rut, first_name, last_name, email, phone, active) VALUES ('19123456-7', 'Daniel', 'Aedo', 'daedo@correo.cl', '+56912345678', true);
INSERT IGNORE INTO members (rut, first_name, last_name, email, phone, active) VALUES ('19765432-1', 'Patricio', 'CÃ©spedes', 'pcespedes@correo.cl', '+56987654321', true);
INSERT IGNORE INTO members (rut, first_name, last_name, email, phone, active) VALUES ('20111222-3', 'Angelo', 'Ponce', 'aponce@correo.cl', '+56911223344', true);
INSERT IGNORE INTO notifications (recipient_email, subject, message, sent_at, status) VALUES ('daedo@correo.cl', 'Bienvenido a Sportmedics', 'Tu cuenta ha sido creada exitosamente.', '2026-05-17 10:00:00', 'SENT');
INSERT IGNORE INTO notifications (recipient_email, subject, message, sent_at, status) VALUES ('pcespedes@correo.cl', 'Aviso de Vencimiento', 'Tu plan vence en 3 dÃ­as.', '2026-05-17 11:30:00', 'SENT');
INSERT IGNORE INTO notifications (recipient_email, subject, message, sent_at, status) VALUES ('daedo@correo.cl', 'Bienvenido a Sportmedics', 'Tu cuenta ha sido creada exitosamente.', '2026-05-17 10:00:00', 'SENT');
INSERT IGNORE INTO notifications (recipient_email, subject, message, sent_at, status) VALUES ('pcespedes@correo.cl', 'Aviso de Vencimiento', 'Tu plan vence en 3 dÃ­as.', '2026-05-17 11:30:00', 'SENT');
INSERT IGNORE INTO appointments (member_id, employee_id, activity_name, scheduled_date, status) VALUES (1, 2, 'EvaluaciÃ³n FÃ­sica Inicial', '2026-06-15T10:00:00', 'SCHEDULED');
INSERT IGNORE INTO appointments (member_id, employee_id, activity_name, scheduled_date, status) VALUES (2, 2, 'Clase de Spinning', '2026-06-15T18:30:00', 'SCHEDULED');
INSERT IGNORE INTO appointments (member_id, employee_id, activity_name, scheduled_date, status) VALUES (3, 2, 'Entrenamiento Personalizado', '2026-06-16T09:00:00', 'SCHEDULED');
INSERT IGNORE INTO appointments (member_id, employee_id, activity_name, scheduled_date, status) VALUES (1, 2, 'EvaluaciÃ³n FÃ­sica Inicial', '2026-06-15T10:00:00', 'SCHEDULED');
INSERT IGNORE INTO appointments (member_id, employee_id, activity_name, scheduled_date, status) VALUES (2, 2, 'Clase de Spinning', '2026-06-15T18:30:00', 'SCHEDULED');
INSERT IGNORE INTO appointments (member_id, employee_id, activity_name, scheduled_date, status) VALUES (3, 2, 'Entrenamiento Personalizado', '2026-06-16T09:00:00', 'SCHEDULED');
INSERT IGNORE INTO subscriptions (name, price, duration_months, active) VALUES ('Plan Mensual BÃ¡sico', 25000, 1, true);
INSERT IGNORE INTO subscriptions (name, price, duration_months, active) VALUES ('Plan Trimestral Pro', 65000, 3, true);
INSERT IGNORE INTO subscriptions (name, price, duration_months, active) VALUES ('Plan Anual VIP', 200000, 12, true);
INSERT IGNORE INTO subscriptions (name, price, duration_months, active) VALUES ('Plan Mensual BÃ¡sico', 25000, 1, true);
INSERT IGNORE INTO subscriptions (name, price, duration_months, active) VALUES ('Plan Trimestral Pro', 65000, 3, true);
INSERT IGNORE INTO subscriptions (name, price, duration_months, active) VALUES ('Plan Anual VIP', 200000, 12, true);
INSERT IGNORE INTO workouts (member_id, teacher_id, name, start_date, end_date, active) VALUES (1, 2, 'Hipertrofia Fase 1', '2026-05-17', '2026-06-17', true);
INSERT IGNORE INTO workout_details (workout_id, exercise_name, muscle_group, sets, reps, rest_seconds, day_of_week) VALUES (1, 'Press de Banca', 'Pecho', 4, 10, 90, 'LUNES');
INSERT IGNORE INTO workout_details (workout_id, exercise_name, muscle_group, sets, reps, rest_seconds, day_of_week) VALUES (1, 'Sentadilla Libre', 'Piernas', 4, 12, 120, 'MIERCOLES');

INSERT IGNORE INTO workouts (member_id, teacher_id, name, start_date, end_date, active) VALUES (1, 2, 'Hipertrofia Fase 1', '2026-05-17', '2026-06-17', true);
INSERT IGNORE INTO workout_details (workout_id, exercise_name, muscle_group, sets, reps, rest_seconds, day_of_week) VALUES (1, 'Press de Banca', 'Pecho', 4, 10, 90, 'LUNES');
INSERT IGNORE INTO workout_details (workout_id, exercise_name, muscle_group, sets, reps, rest_seconds, day_of_week) VALUES (1, 'Sentadilla Libre', 'Piernas', 4, 12, 120, 'MIERCOLES');

